version: 2.1

orbs:
  node: circleci/node@6.3.0

commands:
  setup:
    description: "Setup"
    steps:
      - checkout
      - node/install-pnpm:
          version: '9'
      - run:
          name: Install pnpm dependencies
          command: pnpm install
      - run:
          name: Build
          command: pnpm build

jobs:
  lint:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Lint
          command: pnpm lint
  typecheck:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Typecheck
          command: pnpm typecheck
  publish:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Set NPM Credentials
          command: pnpm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run:
          name: Bump NPM Package Version
          command: ./scripts/bump_npm_version.sh
      - run:
          name: Publish to NPM Registry
          command: pnpm publish --no-git-checks

workflows:
  main:
    jobs:
      - lint
      - typecheck
      - publish:
          context: super-cli-repo
          filters:
            branches:
              only:
                - main